version: "3.8"

services:
  server:
    build: sshserver  
    ports:
      - "2222:22"


  # Random service container 
  frontend:
    build: frontend    
    #ports:
    #- 8080:80
    depends_on:
    - backend

  backend:
    build: backend

